version: '3.9'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: zenghongtu/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            # https://docs.rsshub.app/en/install/#configuration
            # www.example.com 或者 *
            ALLOW_ORIGIN: ${ALLOW_ORIGIN}
            # Http basic authentication 用户名，默认为 usernam3，请务必修改
            HTTP_BASIC_AUTH_NAME: ${HTTP_BASIC_AUTH_NAME}
            # Http basic authentication 密码，默认为 passw0rd，请务必修改
            HTTP_BASIC_AUTH_PASS: ${HTTP_BASIC_AUTH_PASS}
            # 访问密钥 https://docs.rsshub.app/install/#pei-zhi-fang-wen-kong-zhi-pei-zhi-fang-wen-mi-yao-ma
            ACCESS_KEY: ${ACCESS_KEY}
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000' # marked
            PROXY_URI: 'socks5h://warp-socks:9091'
        depends_on:
            - redis
            - browserless # marked

    browserless: # marked
        image: browserless/chrome # marked
        restart: always # marked
        ulimits: # marked
            core: # marked
                hard: 0 # marked
                soft: 0 # marked

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

    warp-socks:
        image: monius/docker-warp-socks:latest
        privileged: true
        volumes:
            - /lib/modules:/lib/modules
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
            net.ipv4.conf.all.src_valid_mark: 1
        healthcheck:
            test: ['CMD', 'curl', '-f', 'https://www.cloudflare.com/cdn-cgi/trace']
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    redis-data:
