version: '3.9'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: zenghongtu/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            # https://docs.rsshub.app/en/install/#configuration
            # www.example.com 或者 *
            ALLOW_ORIGIN: ${ALLOW_ORIGIN}
            # Http basic authentication 用户名，默认为 usernam3，请务必修改
            HTTP_BASIC_AUTH_NAME: ${HTTP_BASIC_AUTH_NAME}
            # Http basic authentication 密码，默认为 passw0rd，请务必修改
            HTTP_BASIC_AUTH_PASS: ${HTTP_BASIC_AUTH_PASS}
            # 访问密钥 https://docs.rsshub.app/install/#pei-zhi-fang-wen-kong-zhi-pei-zhi-fang-wen-mi-yao-ma
            ACCESS_KEY: ${ACCESS_KEY}
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000' # marked
            PROXY_URI: 'socks5://chatgpt-proxy-server-warp:65535'
        depends_on:
            - redis
            - chatgpt-proxy-server-warp
            - browserless # marked

    browserless: # marked
        image: browserless/chrome # marked
        restart: always # marked
        ulimits: # marked
            core: # marked
                hard: 0 # marked
                soft: 0 # marked

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

    chatgpt-proxy-server-warp:
      container_name: chatgpt-proxy-server-warp
      image: linweiyuan/chatgpt-proxy-server-warp
      restart: unless-stopped

volumes:
    redis-data:
